#!/usr/bin/env bash
# Fetch the previous review comment so the next round can reference it.
# Uses the same marker and author check as post-review-comment.sh, taking the latest match.
# Required env: GH_TOKEN, GH_REPO, PR_NUMBER, RUNNER_TEMP
# Optional env: PREV_REVIEW_MAX (defaults to 8000 bytes), GITHUB_OUTPUT
#
# fail-open: losing the previous comment only costs continuity, which is no reason
# to fail the whole review. On failure treat this as round 1 and emit a warning.
# (Contrast with post-review-comment.sh, which is fail-closed: a read failure there
# could duplicate a posted comment, whereas the worst case here is missing context.)
set -euo pipefail

: "${GH_TOKEN:?}"
: "${GH_REPO:?}"
: "${PR_NUMBER:?}"
: "${RUNNER_TEMP:?}"
: "${PREV_REVIEW_MAX:=8000}"

OWNER="${GH_REPO%%/*}"
NAME="${GH_REPO##*/}"
MARKER='<!-- cursor-cli-code-review -->'
PREV_FILE="${RUNNER_TEMP}/prev-review.md"

rm -f "${PREV_FILE}"
round=1

emit_round() {
  if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "round=${round}" >> "${GITHUB_OUTPUT}"
  fi
  echo "::notice::review_round=${round}"
}

if ! pr_json="$(gh api graphql \
  -f query='query($owner:String!,$name:String!,$n:Int!){
    repository(owner:$owner,name:$name){
      pullRequest(number:$n){
        comments(last:100){
          nodes{ databaseId author{login} body }
        }
      }
    }
  }' \
  -F "owner=${OWNER}" \
  -F "name=${NAME}" \
  -F "n=${PR_NUMBER}" 2>&1)"; then
  echo "::warning::Failed to read previous review comments; treating this as round 1 (no continuity context)"
  emit_round
  exit 0
fi

prev_body="$(printf '%s\n' "${pr_json}" | jq -r --arg m "${MARKER}" '
  .data.repository.pullRequest.comments.nodes
  | map(select(.author.login == "github-actions" and (.body | startswith($m))))
  | if length == 0 then empty else (last | .body) end
' 2>/dev/null || true)"

if [ -z "${prev_body}" ]; then
  echo "::notice::No previous review comment found (first round)"
  emit_round
  exit 0
fi

# The footer looks like: _Generated by ... · head=`abc` · round=`3`_
prev_round="$(printf '%s\n' "${prev_body}" \
  | sed -n 's/.*round=`\([0-9][0-9]*\)`.*/\1/p' \
  | tail -n 1)"
if [ -n "${prev_round}" ]; then
  round=$((prev_round + 1))
else
  # Comments posted before v1.2.0 carry no round marker: one round already
  # happened, so count this one as round 2.
  round=2
fi

# Drop the marker line, keep the body, then truncate by bytes so it does not eat
# into the diff budget.
# These two steps are deliberately not a single pipeline: when the body is nothing
# but the marker, grep exits 1, and head -c closing the pipe early hands the
# upstream an EPIPE. Under set -euo pipefail either one would fail this step,
# which contradicts fail-open.
raw_file="${PREV_FILE}.raw"
printf '%s\n' "${prev_body}" | grep -v -F -x "${MARKER}" > "${raw_file}" || true
head -c "${PREV_REVIEW_MAX}" "${raw_file}" > "${PREV_FILE}"

if [ "$(wc -c < "${raw_file}")" -gt "${PREV_REVIEW_MAX}" ]; then
  printf '\n[previous review truncated]\n' >> "${PREV_FILE}"
fi
rm -f "${raw_file}"

echo "::notice::prev_review_bytes=$(wc -c < "${PREV_FILE}")"
emit_round
