#!/usr/bin/env bash
# Upsert PR review comment (github-actions[bot] + marker); update or create.
# Uses GraphQL rather than the REST Issues Comments API: some private repos answer
# 404/403 on GET/PATCH /repos/.../issues/{n}/comments while GraphQL reads and writes fine.
# Required env: GH_TOKEN, GH_REPO, PR_NUMBER, CURSOR_MODEL, HEAD_SHA, RUNNER_TEMP
# Optional env: REVIEW_ROUND (defaults to 1; written into the footer for fetch-prev-review.sh to parse next round)
set -euo pipefail

: "${GH_TOKEN:?}"
: "${GH_REPO:?}"
: "${PR_NUMBER:?}"
: "${CURSOR_MODEL:?}"
: "${HEAD_SHA:?}"
: "${RUNNER_TEMP:?}"
: "${REVIEW_ROUND:=1}"

OWNER="${GH_REPO%%/*}"
NAME="${GH_REPO##*/}"
MARKER='<!-- cursor-cli-code-review -->'

{
  echo "${MARKER}"
  echo
  cat "${RUNNER_TEMP}/cursor-review.md"
  echo
  echo "---"
  echo "_Generated by \`Cursor Code Review\` workflow · model=\`${CURSOR_MODEL}\` · head=\`${HEAD_SHA}\` · round=\`${REVIEW_ROUND}\`_"
} > /tmp/pr-comment.md

# In GraphQL the bot login is github-actions (no [bot] suffix).
# Match on that author plus the marker so nobody can forge it; take the latest match.
if ! pr_json="$(gh api graphql \
  -f query='query($owner:String!,$name:String!,$n:Int!){
    repository(owner:$owner,name:$name){
      pullRequest(number:$n){
        id
        comments(last:100){
          nodes{ id databaseId author{login} body }
        }
      }
    }
  }' \
  -F "owner=${OWNER}" \
  -F "name=${NAME}" \
  -F "n=${PR_NUMBER}")"; then
  echo "::error::Failed to read PR comments (GraphQL; GITHUB_TOKEN permissions may be insufficient)"
  exit 1
fi

EXISTING_ID="$(printf '%s\n' "${pr_json}" | jq -r --arg m "${MARKER}" '
  .data.repository.pullRequest.comments.nodes
  | map(select(.author.login == "github-actions" and (.body | startswith($m))))
  | if length == 0 then empty else (last | .id) end
')"
PR_NODE_ID="$(printf '%s\n' "${pr_json}" | jq -r '.data.repository.pullRequest.id // empty')"
EXISTING_DB_ID="$(printf '%s\n' "${pr_json}" | jq -r --arg m "${MARKER}" '
  .data.repository.pullRequest.comments.nodes
  | map(select(.author.login == "github-actions" and (.body | startswith($m))))
  | if length == 0 then empty else (last | .databaseId | tostring) end
')"

if [[ -z "${PR_NODE_ID}" || "${PR_NODE_ID}" == "null" ]]; then
  echo "::error::Could not resolve the PR node id (check PR_NUMBER=${PR_NUMBER})"
  exit 1
fi

if [[ -n "${EXISTING_ID}" ]]; then
  if gh api graphql \
    -f query='mutation($id:ID!,$body:String!){
      updateIssueComment(input:{id:$id, body:$body}){
        issueComment{ databaseId }
      }
    }' \
    -F "id=${EXISTING_ID}" \
    -F "body=@/tmp/pr-comment.md"; then
    echo "Updated existing review comment #${EXISTING_DB_ID}"
    exit 0
  fi
  echo "::warning::Failed to update the existing review comment; falling back to creating a new one"
fi

if ! create_json="$(gh api graphql \
  -f query='mutation($subjectId:ID!,$body:String!){
    addComment(input:{subjectId:$subjectId, body:$body}){
      commentEdge{
        node{
          ... on IssueComment{ databaseId }
        }
      }
    }
  }' \
  -F "subjectId=${PR_NODE_ID}" \
  -F "body=@/tmp/pr-comment.md")"; then
  echo "::error::Failed to post the review comment (GraphQL; GITHUB_TOKEN permissions may be insufficient)"
  exit 1
fi

NEW_DB_ID="$(printf '%s\n' "${create_json}" | jq -r '.data.addComment.commentEdge.node.databaseId // empty')"
echo "Created new review comment #${NEW_DB_ID}"
